"""
Clinical Chatbot Integration Module
Integration layer for seamless integration with Streamlit and FastAPI apps

Features:
- Session management
- User-friendly interface helpers
- Error handling and fallbacks
- Batch processing
- Export functionality
"""

import os
import json
from typing import Dict, List, Optional, Tuple
from datetime import datetime, timedelta
import sqlite3
from pathlib import Path


# ============================================================================
# SESSION MANAGEMENT
# ============================================================================

class ChatbotSessionManager:
    """Manage chatbot sessions for multiple users"""
    
    def __init__(self, db_path: str = "clinical_conversations.db"):
        self.db_path = db_path
        self.active_sessions: Dict = {}
    
    def create_session(self, patient_id: str, user_id: str) -> Dict:
        """
        Create new session
        
        Args:
            patient_id: Patient identifier
            user_id: Healthcare professional identifier
            
        Returns:
            Session information dict
        """
        session_id = f"{patient_id}_{datetime.now().timestamp()}"
        
        session = {
            "session_id": session_id,
            "patient_id": patient_id,
            "user_id": user_id,
            "created_at": datetime.now().isoformat(),
            "last_activity": datetime.now().isoformat(),
            "status": "active",
            "message_count": 0
        }
        
        self.active_sessions[session_id] = session
        return session
    
    def get_session(self, session_id: str) -> Optional[Dict]:
        """Get session by ID"""
        return self.active_sessions.get(session_id)
    
    def close_session(self, session_id: str):
        """Close session"""
        if session_id in self.active_sessions:
            self.active_sessions[session_id]["status"] = "closed"
            self.active_sessions[session_id]["closed_at"] = datetime.now().isoformat()
    
    def update_activity(self, session_id: str):
        """Update last activity timestamp"""
        if session_id in self.active_sessions:
            self.active_sessions[session_id]["last_activity"] = datetime.now().isoformat()
            self.active_sessions[session_id]["message_count"] += 1


# ============================================================================
# RESPONSE FORMATTING
# ============================================================================

class ResponseFormatter:
    """Format chatbot responses for different interfaces"""
    
    @staticmethod
    def format_for_streamlit(response: str, response_type: str = "default") -> str:
        """
        Format response for Streamlit display
        
        Args:
            response: Raw response text
            response_type: Type of response (default, risk, treatment, monitoring)
            
        Returns:
            Formatted response with markdown
        """
        if response_type == "risk":
            return f"""
### 🔴 Risk Analysis
{response}
"""
        elif response_type == "treatment":
            return f"""
### 💊 Treatment Recommendations
{response}
"""
        elif response_type == "monitoring":
            return f"""
### 📊 Monitoring Plan
{response}
"""
        else:
            return response
    
    @staticmethod
    def format_for_json(
        response: str,
        message_type: str,
        patient_id: str,
        timestamp: str = None
    ) -> Dict:
        """
        Format response as JSON
        
        Args:
            response: Response text
            message_type: Type of message
            patient_id: Patient identifier
            timestamp: Timestamp
            
        Returns:
            JSON-formatted dict
        """
        return {
            "status": "success",
            "patient_id": patient_id,
            "message_type": message_type,
            "response": response,
            "timestamp": timestamp or datetime.now().isoformat(),
            "model": "gpt-4"
        }
    
    @staticmethod
    def format_for_healthcare_record(response: str) -> str:
        """
        Format response for electronic health record (EHR)
        
        Args:
            response: Response text
            
        Returns:
            EHR-compatible formatted text
        """
        return f"""
CLINICAL AI CONSULTATION NOTE
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Format: Temporary consultation only - requires physician review

{response}

DISCLAIMER:
This document was generated by an AI system for clinical support only.
It is NOT a substitute for professional clinical judgment.
Must be reviewed, validated, and approved by qualified healthcare professionals.
"""


# ============================================================================
# CONVERSATION ANALYTICS
# ============================================================================

class ConversationAnalytics:
    """Analyze and generate reports from conversations"""
    
    def __init__(self, db_path: str = "clinical_conversations.db"):
        self.db_path = db_path
    
    def get_conversation_stats(self, patient_id: str) -> Dict:
        """
        Get conversation statistics for patient
        
        Args:
            patient_id: Patient identifier
            
        Returns:
            Statistics dict
        """
        with sqlite3.connect(self.db_path) as conn:
            conn.row_factory = sqlite3.Row
            cursor = conn.cursor()
            
            # Get all conversations
            cursor.execute(
                "SELECT * FROM conversations WHERE patient_id = ?",
                (patient_id,)
            )
            conversations = [dict(row) for row in cursor.fetchall()]
            
            # Get message count per conversation
            cursor.execute("""
                SELECT conversation_id, COUNT(*) as message_count
                FROM messages
                WHERE patient_id = ?
                GROUP BY conversation_id
            """, (patient_id,))
            
            message_counts = {row[0]: row[1] for row in cursor.fetchall()}
            
            return {
                "patient_id": patient_id,
                "total_conversations": len(conversations),
                "total_messages": sum(message_counts.values()),
                "avg_messages_per_chat": (
                    sum(message_counts.values()) / len(conversations)
                    if conversations else 0
                ),
                "message_counts": message_counts,
                "first_conversation": conversations[0]["started_at"] if conversations else None,
                "last_conversation": conversations[-1]["started_at"] if conversations else None
            }
    
    def get_common_topics(self, patient_id: str, limit: int = 10) -> List[Dict]:
        """
        Get most common topics discussed
        
        Args:
            patient_id: Patient identifier
            limit: Number of topics to return
            
        Returns:
            List of topic dictionaries
        """
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            
            cursor.execute("""
                SELECT message_type, COUNT(*) as count
                FROM messages
                WHERE patient_id = ? AND role = 'user'
                GROUP BY message_type
                ORDER BY count DESC
                LIMIT ?
            """, (patient_id, limit))
            
            return [
                {"topic": row[0], "frequency": row[1]}
                for row in cursor.fetchall()
            ]
    
    def generate_summary_report(self, patient_id: str) -> str:
        """
        Generate text summary report of conversations
        
        Args:
            patient_id: Patient identifier
            
        Returns:
            Summary report text
        """
        stats = self.get_conversation_stats(patient_id)
        topics = self.get_common_topics(patient_id)
        
        report = f"""
CLINICAL AI CHATBOT - CONVERSATION SUMMARY REPORT
Patient ID: {patient_id}
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

OVERVIEW:
- Total Conversations: {stats['total_conversations']}
- Total Messages: {stats['total_messages']}
- Average Messages per Chat: {stats['avg_messages_per_chat']:.1f}
- First Conversation: {stats['first_conversation']}
- Last Conversation: {stats['last_conversation']}

COMMON DISCUSSION TOPICS:
"""
        for topic in topics:
            report += f"- {topic['topic']}: {topic['frequency']} messages\n"
        
        report += f"""

NOTES:
This report was generated from AI-assisted clinical consultations.
All conversations have been recorded to the patient's clinical database.
"""
        
        return report


# ============================================================================
# ERROR HANDLING & FALLBACKS
# ============================================================================

class ChatbotErrorHandler:
    """Handle errors and provide fallbacks"""
    
    @staticmethod
    def handle_api_error(error: Exception) -> Dict:
        """
        Handle API errors gracefully
        
        Args:
            error: Exception raised
            
        Returns:
            Error response dict
        """
        error_message = str(error)
        
        if "rate_limit" in error_message.lower():
            return {
                "status": "error",
                "code": "RATE_LIMIT",
                "message": "API rate limit reached. Please try again in a few moments.",
                "fallback": "Please consult with your healthcare provider directly."
            }
        
        elif "api_key" in error_message.lower():
            return {
                "status": "error",
                "code": "API_KEY_ERROR",
                "message": "Service configuration error.",
                "fallback": "Clinical support temporarily unavailable."
            }
        
        elif "connection" in error_message.lower():
            return {
                "status": "error",
                "code": "CONNECTION_ERROR",
                "message": "Network connection error.",
                "fallback": "Unable to connect. Check your internet connection."
            }
        
        else:
            return {
                "status": "error",
                "code": "UNKNOWN_ERROR",
                "message": "An unexpected error occurred.",
                "fallback": "Please try again or contact support."
            }
    
    @staticmethod
    def get_fallback_response(context: str) -> str:
        """
        Provide fallback response when API is unavailable
        
        Args:
            context: Context of the request
            
        Returns:
            Fallback response text
        """
        fallback_responses = {
            "risk": """
CLINICAL GUIDANCE - BASED ON STANDARD PROTOCOLS:

Risk assessment requires detailed clinical evaluation. Please consider:
1. Reviewing current treatment efficacy
2. Monitoring inhibitor development
3. Assessing joint status
4. Evaluating medication adherence

Recommend consulting with hematology specialist for comprehensive risk assessment.
""",
            "treatment": """
STANDARD TREATMENT CONSIDERATIONS:

Treatment decisions should consider:
1. Current factor level and inhibitor status
2. Previous treatment responses
3. Patient-specific factors
4. Available treatment options

Always consult with clinical specialist for treatment decisions.
""",
            "monitoring": """
RECOMMENDED MONITORING SCHEDULE:

Standard monitoring includes:
1. Factor level activity (baseline and periodic)
2. Inhibitor screening (annual minimum)
3. Joint assessments
4. Viral marker monitoring if indicated
5. Medication adherence review

Coordinate with your healthcare team for personalized schedule.
"""
        }
        
        return fallback_responses.get(
            context,
            "Clinical support temporarily unavailable. Please consult with your healthcare provider."
        )


# ============================================================================
# EXPORT & REPORTING
# ============================================================================

class ConversationExporter:
    """Export conversations in various formats"""
    
    def __init__(self, db_path: str = "clinical_conversations.db"):
        self.db_path = db_path
    
    def export_to_json(self, conversation_id: int, output_path: str = None) -> str:
        """
        Export conversation to JSON
        
        Args:
            conversation_id: Conversation ID
            output_path: File path to save
            
        Returns:
            JSON string
        """
        with sqlite3.connect(self.db_path) as conn:
            conn.row_factory = sqlite3.Row
            cursor = conn.cursor()
            
            cursor.execute(
                "SELECT * FROM messages WHERE conversation_id = ? ORDER BY timestamp ASC",
                (conversation_id,)
            )
            
            messages = [dict(row) for row in cursor.fetchall()]
            
            export_data = {
                "conversation_id": conversation_id,
                "exported_at": datetime.now().isoformat(),
                "message_count": len(messages),
                "messages": messages
            }
            
            json_str = json.dumps(export_data, indent=2, default=str)
            
            if output_path:
                Path(output_path).write_text(json_str)
            
            return json_str
    
    def export_to_csv(self, conversation_id: int, output_path: str) -> str:
        """
        Export conversation to CSV
        
        Args:
            conversation_id: Conversation ID
            output_path: File path to save
            
        Returns:
            CSV string
        """
        import csv
        from io import StringIO
        
        with sqlite3.connect(self.db_path) as conn:
            conn.row_factory = sqlite3.Row
            cursor = conn.cursor()
            
            cursor.execute(
                "SELECT * FROM messages WHERE conversation_id = ? ORDER BY timestamp ASC",
                (conversation_id,)
            )
            
            rows = cursor.fetchall()
            
            output = StringIO()
            if rows:
                writer = csv.DictWriter(output, fieldnames=dict(rows[0]).keys())
                writer.writeheader()
                for row in rows:
                    writer.writerow(dict(row))
            
            csv_str = output.getvalue()
            
            if output_path:
                Path(output_path).write_text(csv_str)
            
            return csv_str
    
    def export_text_summary(self, conversation_id: int, output_path: str = None) -> str:
        """
        Export conversation as readable text summary
        
        Args:
            conversation_id: Conversation ID
            output_path: File path to save
            
        Returns:
            Text summary
        """
        with sqlite3.connect(self.db_path) as conn:
            conn.row_factory = sqlite3.Row
            cursor = conn.cursor()
            
            cursor.execute(
                "SELECT * FROM messages WHERE conversation_id = ? ORDER BY timestamp ASC",
                (conversation_id,)
            )
            
            messages = [dict(row) for row in cursor.fetchall()]
            
            text = f"""
CLINICAL AI CHATBOT CONVERSATION EXPORT
Conversation ID: {conversation_id}
Exported: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Total Messages: {len(messages)}

{'='*70}

"""
            
            for i, msg in enumerate(messages, 1):
                role = "👤 PATIENT/USER" if msg["role"] == "user" else "🤖 AI ASSISTANT"
                timestamp = msg["timestamp"]
                content = msg["content"]
                
                text += f"""
[Message {i}] {role}
Time: {timestamp}
Type: {msg.get('message_type', 'N/A')}

{content}

{'-'*70}

"""
            
            if output_path:
                Path(output_path).write_text(text)
            
            return text


# ============================================================================
# QUICK START HELPERS
# ============================================================================

def quick_chat_setup() -> Dict:
    """
    Quick setup for chatbot integration
    
    Returns:
        Setup configuration dict
    """
    config = {
        "api_key": os.getenv("OPENAI_API_KEY"),
        "models": ["gpt-4", "gpt-3.5-turbo"],
        "database": "clinical_conversations.db",
        "session_manager": ChatbotSessionManager(),
        "response_formatter": ResponseFormatter(),
        "error_handler": ChatbotErrorHandler(),
        "exporter": ConversationExporter(),
        "analytics": ConversationAnalytics()
    }
    
    # Validate configuration
    if not config["api_key"]:
        print("⚠️ Warning: OPENAI_API_KEY not set. Chatbot may not work.")
    
    print("✅ Chatbot components initialized")
    return config


# ============================================================================
# STREAMLIT INTEGRATION HELPERS
# ============================================================================

def create_streamlit_chat_interface() -> Dict:
    """
    Helper to create Streamlit chat interface
    
    Returns:
        Interface configuration
    """
    try:
        import streamlit as st
        
        return {
            "st": st,
            "chat_container": st.container,
            "input_widget": st.text_input,
            "button_widget": st.button,
            "display_message": st.write,
            "display_error": st.error,
            "display_success": st.success,
            "display_info": st.info
        }
    except ImportError:
        return {"error": "Streamlit not installed"}


# ============================================================================
# EXAMPLE INTEGRATION CODE
# ============================================================================

STREAMLIT_INTEGRATION_EXAMPLE = """
# Streamlit Integration Example

import streamlit as st
from clinical_ai_chatbot import ClinicalAIChatbot, PatientContext
from clinical_chatbot_integration import (
    ChatbotSessionManager, ResponseFormatter, ConversationAnalytics
)

st.set_page_config(page_title="Clinical AI Assistant", layout="wide")

@st.cache_resource
def init_chatbot():
    return ClinicalAIChatbot()

chatbot = init_chatbot()
session_mgr = ChatbotSessionManager()
formatter = ResponseFormatter()

# Patient selection
patient_id = st.selectbox("Select Patient", ["PAT-001", "PAT-002", "PAT-003"])

# Create session
if "session_id" not in st.session_state:
    session = session_mgr.create_session(patient_id, "DR-SMITH")
    st.session_state.session_id = session["session_id"]

# Chat interface
st.subheader("Clinical Support Chat")

user_input = st.text_input("Your Question:", placeholder="Ask for clinical recommendations...")

if user_input:
    session_mgr.update_activity(st.session_state.session_id)
    
    try:
        response = chatbot.chat(user_input)
        st.success(formatter.format_for_streamlit(response))
    except Exception as e:
        st.error(f"Error: {str(e)}")

# Conversation history
if st.checkbox("Show Conversation History"):
    history = chatbot.db.get_conversation_history(chatbot.conversation_id)
    for msg in history:
        if msg["role"] == "user":
            st.write(f"👤 **Patient**: {msg['content']}")
        else:
            st.write(f"🤖 **AI**: {msg['content']}")
"""
